### PR TITLE
Adds nullptr checking when caching levels

### PR DESCRIPTION
**Pull request by ivaylo-disguise**
Assets are loaded and cast to UWorld. Under certain situations, such as copy-pasting world assets manually, this procedure may return a nullptr. Without nullptr checking, an access violation crashes Unreal Engine.

Here we catch nullptr and log an appropriate error message for the user.

RSP-348

### CODE REVIEW

**Review by josharms-disguise — APPROVED** [review]
lgtm

**Review by Jordan-Goulet-Disguise-One — APPROVED** [review]
**QA Passed**

**Comment by MunWolf** [comment]
Looks like there is an issue with spacing (tabs vs spaces)

**Comment by ivaylo-disguise** [comment]
> Looks like there is an issue with spacing (tabs vs spaces)

true, I'll check what happened there.

**Pull request merged**
