### PR TITLE
Fix for Exposed Parameters not Appearing in this Version

### PR DESCRIPTION
**Pull request by josharms-disguise**
Fixed issue in this version where not all exposed parameters were being written to schema file

### CODE REVIEW

**Review by MunWolf — APPROVED** [review]
LGTM

**Comment by josharms-disguise** [comment]
DSOF-26563

**Review by pkevin-disguise — APPROVED** [review]
lgtm

**Review by Jordan-Goulet-Disguise-One — APPROVED** [review]
**QA Passed,**

**Pull request merged**
