### PR TITLE
Plugin MultiUserClient Fails To Load When Launching A Project With The RenderStream Plugin

### PR DESCRIPTION
**Pull request by josharms-disguise**
A plugin that MultiUserClient requires does not get enabled by default so this change forces that plugin (ConcertSyncClient) to be enabled in the plugin template so everything can load properly.

### CODE REVIEW

**Comment by twhittock-disguise** [comment]
we don't depend on multi user client, right? this should only be enabled when the multi user client plugin is enabled... is there nowhere we can do that? I'd prefer not to bloat our dependencies for something optional.

**Comment by josharms-disguise** [comment]
> we don't depend on multi user client, right? this should only be enabled when the multi user client plugin is enabled... is there nowhere we can do that? I'd prefer not to bloat our dependencies for something optional.

It's required for nDisplay but in 5.4 it doesn't get enabled automatically for some reason

**Review by pkevin-disguise — APPROVED** [review]
It's a little bit strange that we have to manually load a plugin that the multi user plugin depend on and not manually load the multi user plugin directly, but I guess the multi user plugin isn't enabling its dependencies correctly.

LGTM

**Comment by josharms-disguise** [comment]
> It's a little bit strange that we have to manually load a plugin that the multi user plugin depend on and not manually load the multi user plugin directly, but I guess the multi user plugin isn't enabling its dependencies correctly.
> 
> LGTM

I have been told they are planning to fix this in 5.5

**Comment by Jordan-Goulet-Disguise-One** [comment]
**QA passed.**

**Review by Jordan-Goulet-Disguise-One — APPROVED** [review]
QA passed.

**Pull request merged**
